// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDp6rAJOd4Z-8gVCKtoQ6qty2BCW08zpx0',
    appId: '1:671494174327:web:8b0885a4f8018497d1f872',
    messagingSenderId: '671494174327',
    projectId: 'foodapp-37558',
    authDomain: 'foodapp-37558.firebaseapp.com',
    storageBucket: 'foodapp-37558.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0RR279uRZ2qOAA0TtSkK20eh5FjO4h0E',
    appId: '1:671494174327:ios:0fffb01c140e4f35d1f872',
    messagingSenderId: '671494174327',
    projectId: 'foodapp-37558',
    storageBucket: 'foodapp-37558.appspot.com',
    iosBundleId: 'com.example.foodapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0RR279uRZ2qOAA0TtSkK20eh5FjO4h0E',
    appId: '1:671494174327:ios:0fffb01c140e4f35d1f872',
    messagingSenderId: '671494174327',
    projectId: 'foodapp-37558',
    storageBucket: 'foodapp-37558.appspot.com',
    iosBundleId: 'com.example.foodapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDp6rAJOd4Z-8gVCKtoQ6qty2BCW08zpx0',
    appId: '1:671494174327:web:f25bb10c754776bfd1f872',
    messagingSenderId: '671494174327',
    projectId: 'foodapp-37558',
    authDomain: 'foodapp-37558.firebaseapp.com',
    storageBucket: 'foodapp-37558.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCh58oV60_KIGhLl6kcLdO3AsyvXsR9v4o',
    appId: '1:671494174327:android:fd67e15dce55b530d1f872',
    messagingSenderId: '671494174327',
    projectId: 'foodapp-37558',
    storageBucket: 'foodapp-37558.appspot.com',
  );

}